### ISSUE TITLE
FEATURE REQUEST: Display social share counts for document analytics

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-googleanalytics#11]
Jira issue originally created by user @hlubek:

A new widget for document analytics should display social share counts for Twitter, Facebook, Google+.

A service like https://www.sharedcount.com/ could be used to fetch the share count.

 Jira-URL: https://jira.neos.io/browse/NEOS-867

**Comment by Sebobo** [comment]
This should be added via a separate package to also work with other tracking packages.
