### ISSUE TITLE
Error with Neos 3.0.3 on doctrine:migrate 

### ISSUE THREAD

**Issue by ru3fu5z** [neos/neos-googleanalytics#22]
related: https://discuss.neos.io/t/error-running-doctrine-migrate-after-installing-neos-googleanalytics/2200
What i did:

Installing neos/googleanalytics 2.0.1 on my Neos 3.0.3 installation.
On the ./neos/administration/googleAnalytics Page got a error:
#0: A table or view seems to be missing from the database.
running doctrine:migrate and got the following error:

`Exception in line 128 of /var/www/Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php: An exception occurred while executing 'ALTER TABLE typo3_neos_googleanalytics_domain_model_siteconfiguration ADD CONSTRAINT FK_D675F674694309E4 FOREIGN KEY (site) REFERENCES typo3_neos_domain_model_site (persistence_object_identifier) ON DELETE CASCADE':

SQLSTATE[HY000]: General error: 1005 Can't create table neos.#sql-38b_90 (errno: 150 "Foreign key constraint is incorrectly formed")

**Comment by kdambekalns** [comment]
This is caused by the tables no longer being named like that from Neos 3.0 onwards. We need to fix this, there is no easy workaround, unfortunately.

What you can try, though, is to adjust the migration file to contain the correct names (`neos_…`) and try again.

**Comment by kdambekalns** [comment]
"Note to self": We have a migration to rename existing tables to the new names, but we must adjust the previous migrations to do "the right thing" when on Neos 3.0…

**Comment by rolandschuetz** [comment]
This is already fixed here https://github.com/rolandschuetz/neos-googleanalytics/commit/d92edaad28a443ee772efe50aede0257033870fe
