### ISSUE TITLE
Backend: chart-widget have a scrollbar

### ISSUE THREAD

**Issue by nbosshard** [neos/neos-googleanalytics#30]
In Firefox we have a scrollbar by the chart-widget.
![grafik](https://user-images.githubusercontent.com/7582822/32321437-6db26e2a-bfc1-11e7-8c10-6f50408feecb.png)

It looks that the SVG i little bit to wide.

OS: Windows 10
Browser: Firefox v56.0.2

**Comment by crydotsnake** [comment]
Does the problem still exist?
