### ISSUE TITLE
Where to configure the package?

### ISSUE THREAD

**Issue by danaron** [neos/neos-googleanalytics#41]
I did install the Package on Neos 3.2.0 and get the error:
Missing setting "Neos.GoogleAnalytics.authentication.clientId"
As soon as I change  the Settings.yaml in Neos.GoogleAnalytics/Configruation the hole system crashes. I dont get what to fill in there:
    authentication:
      # Application name for the consent screen
      applicationName: 'Neos CMS'
      # "Client ID" of the OAuth 2.0 "Client ID for web application"
      clientId: ~
      # "Client Secret" of the OAuth 2.0 "Client ID for web application"
      clientSecret: ~
      # "API Key" of the Public API access credential "Key for server applications"
      developerKey: ~
And here:
    sites: [Mysitepackage]
      ## All site specific settings are indexed by site node name
      #
      #Mysitepackage:
         trackingId: 'UA-00000000-1'
         profileId: '000000000'
Thank you for your help.
Best regards
Danaron

**Comment by rolandschuetz** [comment]
You can find a description of how to set it up here:
https://neos-google-analytics-integration.readthedocs.io/en/stable/

**Comment by kdambekalns** [comment]
For me this is not really an issue. The README clearly links to the documentation, that documentation is inside the package, so… and it is rather extensive.
