### ISSUE TITLE
Create documentation for the Google Analytics integration

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-googleanalytics#5]
Jira issue originally created by user @hlubek:
- [x] How to set up a Google Account / create an app (with screenshots on where to find the id / secret)
- [ ] How to configure metrics for node types
- [ ] How to add custom metrics / customize metrics
  
  Jira-URL: https://jira.neos.io/browse/NEOS-1327

**Comment by rolandschuetz** [comment]
What are these metrics?

**Comment by Sebobo** [comment]
Will close this for now. New issues should specify specific requirements.
