### ISSUE TITLE
Move statistics into separate package

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-googleanalytics#56]
* Create new package for statistics
* Upgrade statistics package to get rid of OAuth Login 
* New package should use Flowpack.GoogleApiClient

**Comment by Sebobo** [comment]
OAuth was removed in #54 and `Flowpack.GoogleApiClient` is now being used.
We keep the statistics in here for now.

**Comment by Sebobo** [comment]
I have no real opinion about this as most of my customers don't use this package anymore or have no need of anything else besides the Tag Manager script.

If we separate the statistics we could also simply delete them, as I think the separate package wouldn't get much love and just causes more maintenance.
Having a statistics package that is independent of the vendor could be more interesting though as it could also cover the Matomo integration and improve upon that. But I wonder if any customer or agency is interested in having this improved.

**Comment by dlubitz** [comment]
> But I wonder if any customer or agency is interested in having this improved.
Me too. See: 
https://neos-project.slack.com/archives/C050C8FEK/p1707420490600259

> If we separate the statistics we could also simply delete them
If my assumption is correct and we need to re-implement it for GA4 anyways, I'd also go this way. If not, I think it's initally not that effort to extract it into a separate package. Maybe we can move out of neos namespace (e.g. flowpack or someone how want's to take care).
