### ISSUE TITLE
Google Analytics inspector tab causes many XHR requests

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-googleanalytics#6]
Jira issue originally created by user @robertlemke:

Right now, the Google Analytics inspector tab triggers several XHR requests for gathering the statistics from Google even if the tab is not active. Since the standard case will be that editors navigate through their site having using other tabs, it would be good if the GA inspector tab could only trigger these request when the tab is activated.

 Jira-URL: https://jira.neos.io/browse/NEOS-1354

**Comment by rolandschuetz** [comment]
The new UI implements this.
