### ISSUE TITLE
Backend module throws Undefined property flashMessageContainer error

### ISSUE THREAD

**Issue by hphoeksma** [neos/neos-googleanalytics#64]
Affected versions:
Neos 5.0.5

**Comment by markusguenther** [comment]
Thanks for reporting that issue and great that you are still around in the neos world :)

**Comment by hphoeksma** [comment]
Thanks @markusguenther :-) Yes I am still around! Would love to attend a code sprint again soonish!

**Comment by markusguenther** [comment]
Would be awesome :)
Christian is planing something in the Duesseldorf Area, would not be so far for you ;)
