### ISSUE TITLE
Undefined index: character_set_name

### ISSUE THREAD

**Issue by crydotsnake** [neos/neos-googleanalytics#71]
# Bug Description:

I cloned the [Neos-Skeleton](https://github.com/code-q-web-factory/Neos-Skeleton) Package, after that i changed to the project folder and then i run the `composer install` command. All fine, no errors!. But in the last setup step i get this error message:

![googleanalyticserror](https://user-images.githubusercontent.com/39345336/82894987-cab23500-9f53-11ea-84b5-4fb92f5af3ff.png)

Maybe it has something todo with the Database Charset, but i created the database in the Neos installer. 

### MySQL Version:
`mysql  Ver 8.0.19 for osx10.15 on x86_64 (Homebrew)`

### Composer Version:
`Composer version 1.10.6 2020-05-06 10:28:10`

### Operating System
MacOS Catalina

**Comment by Sebobo** [comment]
This is fixed in #70

**Comment by Sebobo** [comment]
Solved in 3.2.1

**Comment by crydotsnake** [comment]
Okay, thanks!.
