### ISSUE TITLE
googleapiclient is for Neos 6 only 

### ISSUE THREAD

**Issue by markssarGit** [neos/neos-googleanalytics#75]
Not Compatible with Neos 7.*, receive composer error in installation process:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - flowpack/googleapiclient 1.0.0 requires neos/flow ~5.0 || dev-master -> found neos/flow[5.0.0, ..., 5.3.22] but the package is fixed to 7.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - flowpack/googleapiclient 1.1.0 requires neos/flow ~5.0 || ~6.0 || dev-master -> found neos/flow[5.0.0, ..., 5.3.22, 6.0.0, ..., 6.3.5] but the package is fixed to 7.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - neos/googleanalytics 3.3.0 requires flowpack/googleapiclient ^1.0 -> satisfiable by flowpack/googleapiclient[1.0.0, 1.1.0].
    - Root composer.json requires neos/googleanalytics ^3.3 -> satisfiable by neos/googleanalytics[3.3.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by jonnitto** [comment]
I think this is more an issue of Flowpack.GoogleApiClient. I've created an [issue](https://github.com/Flowpack/Flowpack.GoogleApiClient/issues/3) for that

**Comment by jonnitto** [comment]
Should be fixed with https://github.com/Flowpack/Flowpack.GoogleApiClient/releases/tag/1.2.0
