### ISSUE TITLE
FEATURE: Google Analytics Data API for GA4

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-googleanalytics#85]
The used **Google Analytics Reporting API** to fetch data for the statistics in Neos does not support GA4 properties.

> Note: This API does not support [Google Analytics 4 (GA4)](https://support.google.com/analytics/answer/9325020) properties. Please use the [Google Analytics Data API](https://developers.google.com/analytics/devguides/reporting/data/v1) to access the new reporting features for GA4 properties.

As UA properties reached there EOL, it would be good to replace the **Google Analytics Reporting API** with the succussor **Google Analytics Data API**.

Google Analytics Reporting API (old): https://developers.google.com/analytics/devguides/reporting/core/v4
Google Analytics Data API (new): https://developers.google.com/analytics/devguides/reporting/data/v1

**Comment by paavo** [comment]
Sadly the Plugin is not working anymore in the Neos Backend as Google requires GA4.
Are there any plans to fix this?

Otherwise i suggest to remove the Reporting-Part and just us it for Tracking Setup. 
_BUT having Analytics Data in the Backend was always a nice feature to convince people Neos is the right CMS for them._ 

Who is in charge for this package?
Maybe we can do a funding round to make this working again?
@Sebobo @kdambekalns

**Comment by Sebobo** [comment]
I can take a look at the new api and try to come up with an estimate. Sadly I don't use GA myself anymore and my customers also mostly stopped and one just uses the tracking part but not the data.

**Comment by paavo** [comment]
Thanks @Sebobo 
As the whole Reporting-Part is not working anymore, would you accept a PR to remove this parts for now?

Finally `neos/neos-googleanalytics` would become a pretty basic, but still pretty necessary (multi-sites) Analytics-Tracking Plugin.

**Comment by Sebobo** [comment]
@paavo isn't it easier for now to just disable the mixins in your site for now and updating the readme of this package with a note? Or we disable the mixins by default for now.
Not sure if removing everything via a PR is helping much. 

Honestly this package should not be in the Neos namespace and probably be deprecated. And then have a Flowpack or simply a community package. 10 years ago this was much more relevant for everyone.

Then we can still see if providing a PR with a "bugfix" with the new API support is possible. Didn't have the time/brain yet to look into the API migration guide.
